import type { Movie, MembershipRequest } from './types';

export const mockMovies: Movie[] = [
  {
    id: '1',
    title: 'Зүрхний Хилэн',
    description: '1945 оны чөлөөлөх дайны хүнд бэрх цаг үеийг харуулсан Монголын уран сайхны кино.',
    year: 2017,
    genres: ['Дайн', 'Түүхэн', 'Драм'],
    duration: 124,
    thumbnailUrl: 'https://placehold.co/600x400',
    videoUrl: '',
    isPublished: true,
  },
  {
    id: '2',
    title: 'Ану Хатан',
    description: 'Зүүнгарын хаант улсын хатан Анугийн эх орныхоо төлөө хийсэн тэмцлийг харуулсан түүхэн кино.',
    year: 2013,
    genres: ['Түүхэн', 'Адал явдалт'],
    duration: 110,
    thumbnailUrl: 'https://placehold.co/600x401',
    videoUrl: '',
    isPublished: true,
  },
  {
    id: '3',
    title: 'Бодлын Худалдаачин',
    description: 'Өнөөгийн нийгэм дэх хүмүүсийн шунал, ёс суртахууныг хөндсөн драм.',
    year: 2018,
    genres: ['Драм', 'Гэмт хэрэг'],
    duration: 95,
    thumbnailUrl: 'https://placehold.co/600x402',
    videoUrl: '',
    isPublished: true,
  },
  {
    id: '4',
    title: 'Миний Ах Атаман',
    description: 'Ах дүүсийн харилцаа, нөхөрлөл, урвалтын тухай өгүүлнэ.',
    year: 2019,
    genres: ['Инээдэм', 'Драм'],
    duration: 105,
    thumbnailUrl: 'https://placehold.co/600x403',
    videoUrl: '',
    isPublished: true,
  },
  {
    id: '5',
    title: 'Үргээлэг',
    description: 'Байгаль хамгаалал, хууль бус ан агнуурын эсрэг тэмцлийг харуулсан адал явдалт кино.',
    year: 2014,
    genres: ['Адал явдалт', 'Триллэр'],
    duration: 130,
    thumbnailUrl: 'https://placehold.co/600x404',
    videoUrl: '',
    isPublished: false,
  },
  {
    id: '6',
    title: 'Single Ladies 3',
    description: 'Ганц бие бүсгүйчүүдийн хөгжилтэй, адал явдалт түүхийг өгүүлэх инээдмийн кино.',
    year: 2020,
    genres: ['Инээдэм', 'Романтик'],
    duration: 98,
    thumbnailUrl: 'https://placehold.co/600x405',
    videoUrl: '',
    isPublished: true,
  },
];

export const mockMembershipRequests: MembershipRequest[] = [
  {
    id: 'req1',
    uid: 'user1',
    messengerProfileUrl: 'https://m.me/user.one',
    status: 'pending',
    createdAt: new Date('2023-10-26T10:00:00Z'),
  },
  {
    id: 'req2',
    uid: 'user2',
    messengerProfileUrl: 'https://m.me/user.two',
    note: 'Гишүүн болох хүсэлтэй байна.',
    status: 'approved',
    createdAt: new Date('2023-10-25T11:30:00Z'),
    reviewedAt: new Date('2023-10-25T15:00:00Z'),
    reviewedBy: 'adminUser',
  },
  {
    id: 'req3',
    uid: 'user3',
    messengerProfileUrl: 'https://m.me/user.three',
    status: 'rejected',
    createdAt: new Date('2023-10-24T09:00:00Z'),
    reviewedAt: new Date('2023-10-24T12:00:00Z'),
    reviewedBy: 'adminUser',
  },
];
